config/routes.rb
Rails.application.routes.draw do
 
  resources :user_stocks,only:[:create,:destroy]
  resources :friendships,only:[:create,:destroy]
  
  
  devise_for :users
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'my_portfolio',to:'users#my_portfolio'
  get 'search_stock',to:'stocks#quote',as: 'search_stock'

  get 'my_friends',to:'users#my_friends'
  get 'search_friend',to:'users#search',as: 'search_friend'


  # get 'Stocks',to:'stocks#stock_symbols'
 

  # get 'search',to:'stocks#symbol_search'
  #  get '_search/:ticker_symbol',to:'stocks#search'
  resources :users,only:[:show]
 get 'similarity',to:'stocks#similarity_index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/friends/_list.html.erb
<% if !@tracking_friends.empty? %>
<div class="row ">
    <div class="col-9">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
                <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @tracking_friends.each do |friend| %>
                <tr>
                <td scope="row"><%= friend.first_name %></td>
                <td><%= friend.last_name %></td>
                <td><%= friend.email %></td>
                <td><%= link_to 'Remove Following', friendship_path(friend.id), data: {
                    turbo_method: :delete,                    turbo_confirm: "Are you sure?"
                  }, class: "btn btn-warning"   %>
                 <%= link_to "View Profile",user_path(friend.id),class:"btn btn-success"%>
                 </td>
                </tr>
                <%end%>
            </tbody>
        </table>
    </div> 
</div>
<%end%>