config/routes.rb
Rails.application.routes.draw do
 
  resources :user_stocks,only:[:create,:destroy]
  resources :friendships,only:[:create,:destroy]
  
  
  devise_for :users
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'my_portfolio',to:'users#my_portfolio'
  get 'search_stock',to:'stocks#quote',as: 'search_stock'

  get 'my_friends',to:'users#my_friends'
  get 'search_friend',to:'users#search',as: 'search_friend'


  # get 'Stocks',to:'stocks#stock_symbols'
 

  # get 'search',to:'stocks#symbol_search'
  #  get '_search/:ticker_symbol',to:'stocks#search'
  resources :users,only:[:show]
 get 'similarity',to:'stocks#similarity_index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users,through: :user_stocks
  validates :name,:ticker, presence: true
  
  def self.new_lookup(ticker_symbol)
    finnhub_client = FinnhubRuby::DefaultApi.new
    begin
      profile = finnhub_client.company_profile2({symbol: ticker_symbol.upcase})
      quote = finnhub_client.quote(ticker_symbol)
      new(
        ticker: ticker_symbol.upcase,
        name: profile.name,
        ast_price: quote.c
      )
    rescue => exception
       
      Rails.logger.error "Error fetching data for ticker #{ticker_symbol}: #{exception.message}"
      return nil
    end
  end
  def self.check_db(ticker_symbol)
    where(ticker:ticker_symbol).first
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
   
    # def stock_symbols
    #     market = params[:market] || 'US'
    #     @stocks = FINNHUB_CLIENT.stock_symbols(market)
    # end
    def quote
        if params[:stock].present?
            # ticker_symbol = params[:stock]
            # begin
            
            #     @forex_rates = FINNHUB_CLIENT.quote(ticker_symbol)        
            #     # render plain:   @forex_rates
                
            #     company_name=FINNHUB_CLIENT.company_profile2({symbol: ticker_symbol})
            #     if @forex_rates.c != 0.0
            #         @stock=Stock.new(ticker:ticker_symbol,name:company_name.name,ast_price: @forex_rates.c)
                   
            #         respond_to do |format|                        
            #             format.js{render partial:'users/stocksearchResult'}
            #         end
            #         #  render 'users/my_portfolio'
            #     else
            #         respond_to do |format|
            #             flash[:alert]='Please Enter Valid Ticker To Search'
            #             format.html { render 'users/my_portfolio' }
            #             format.js{render partial:'users/stocksearchResult'}
            #         end
                    
            #     end
            # rescue => e
            #     respond_to do |format|
            #          flash[:alert]= "Something went wrong: #{e.message}"
            #         format.html { render 'users/my_portfolio' }
            #         format.js{render partial:'users/stocksearchResult'}
            #     end
            # end

            @stock = Stock.new_lookup(params[:stock])
            
           
            if @stock.ast_price  != 0.0
                respond_to do |format|  
                    format.js { render partial:'users/stocksearchResult' }
                end
            else 
                flash.now[:alert] = 'Please Enter Valid Ticker To Search'
                respond_to do |format|
                    format.js { render partial: 'users/stocksearchResult' }
                end

            end
            
           
        else
            respond_to do |format|
                flash.now[:alert]='Please Enter Valid Ticker To Search'
                format.js{render partial:'users/stocksearchResult'}
            end


        end
    end
    # def symbol_search
    #     @results = FINNHUB_CLIENT.symbol_search('AAPL')
    #     render plain: @results
    # end

    # def similarity_index
    #     @similarity_index = FINNHUB_CLIENT.similarity_index({ symbol: 'AAPL' })
    #     Rails.logger.error("Finnhub API Error: #{e.message}")
    # end
    
    # def search
    #     ticker_symbol = params[:ticker_symbol]
    #     @forex_rates = FINNHUB_CLIENT.quote(ticker_symbol)
    #     render plain: @forex_rates
    # end
end

app/views/stocks/_list.html.erb
<div class="row ">
    <div class="col-9">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                <th scope="col">Ticker</th>
                <th scope="col">Name</th>
                <th scope="col">Ast. Price</th>
                <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @tracked_stocks.each do |stock| %>
                        <tr>
                        <th scope="row"><%= stock.ticker %></th>
                        <td><%= stock.name %></td>
                        <td><%= stock.ast_price %></td>
                        <td>

                         <% if current_user.can_track_stock?(stock.ticker)%>
                                <%= link_to 'Add To Portfolio',user_stocks_path(user: current_user,ticker:stock.ticker),class:"btn btn-success",method: :post%>
                        <%elsif current_user.id != @user.id%>
                            <span class="badge text-bg-success">
                                You are already tracking
                                <% if !current_user.under_stock_limit? %>
                                        8 stocks
                                <%end%>
                                <% if  @user.stock_already_tracked?(stock.ticker) %>
                                        this stock
                                <%end%>
                            </span>
                        <%end%>




                        <% if current_user.id == @user.id %>
                            <%= link_to 'Remove',user_stock_path(stock), data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure?"
                            }, class: "btn btn-warning"   %>
                            </tr>
                            
                        <%end%>
                       
                    
                        </td>
                <%end%>
            </tbody>
        </table>
    </div>
</div>

app/views/stocks/stock_symbols.html.erb
<div class="container mt-5">
    <h1 class="mb-4">Stock Data</h1>
    <table class="table table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Description</th>
          <th>Display Symbol</th>
          <th>Symbol</th>
          <th>Type</th>
          <th>MIC</th>
          <th>FIGI</th>
          <th>Share Class FIGI</th>
          <th>Currency</th>
        </tr>
      </thead>
      <tbody>
        <% @stocks.each do |stock| %>
          <tr>
            <td><%= stock.description%></td>
            <td><%= stock.display_symbol%></td>
            <td><%= stock.symbol %></td>
            <td><%= stock.type %></td>
            <td><%= stock.mic %></td>
            <td><%= stock.figi %></td>
            <td><%= stock.share_class_figi %></td>
            <td><%= stock.currency %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>