config/routes.rb
Rails.application.routes.draw do
 
  resources :user_stocks,only:[:create,:destroy]
  resources :friendships,only:[:create,:destroy]
  
  
  devise_for :users
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'my_portfolio',to:'users#my_portfolio'
  get 'search_stock',to:'stocks#quote',as: 'search_stock'

  get 'my_friends',to:'users#my_friends'
  get 'search_friend',to:'users#search',as: 'search_friend'


  # get 'Stocks',to:'stocks#stock_symbols'
 

  # get 'search',to:'stocks#symbol_search'
  #  get '_search/:ticker_symbol',to:'stocks#search'
  resources :users,only:[:show]
 get 'similarity',to:'stocks#similarity_index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_stocks
  has_many :stocks,through: :user_stocks
  has_many :friendships
  has_many :friends ,through: :friendships
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  def stock_already_tracked?(ticker_symbol)
    stock=Stock.check_db(ticker_symbol)
    return false unless stock 
    stocks.where(id:stock.id).exists?

  end
 def expect_current_user(collection_friends)
  collection_friends.reject {|user| user.id == self.id}

 end

  def under_stock_limit?
    stocks.count < 8
  end

  def can_track_stock?(ticker_symbol)
    
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end
  def full_name
    if first_name || last_name
      "#{first_name} #{last_name}" 
    else
    "Anonymous"
    end
  end
  def not_friends_with?(friend_id)
    !self.friends.where(id:friend_id).exists?
  end

  def self.search(param)
    param.strip! 
    to_send_back=(first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    returmn nil unless to_send_back
    to_send_back
  end
  def self.first_name_matches(param)
    where("first_name LIKE ?","%#{param}%")
  end
  def self.last_name_matches(param)
    where("last_name LIKE ?","%#{param}%")
  end
  def self.email_matches(param)
    where("email LIKE ?","%#{param}%")
  end

  # def self.matches(field_name,param)
  #   where("#{field_name} LIKE ?","%#{param}%")
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def my_portfolio
    @user=current_user
    @tracked_stocks= current_user.stocks
  end
  def my_friends
    @tracking_friends= current_user.friends
  end

  def show
    
    @user=User.find(params[:id])
    @tracked_stocks=  @user.stocks

  end
  def search
    if params[:friend].present?
      @friends=User.search(params[:friend])
      @friends=current_user.expect_current_user(@friends)
      if @friends
        respond_to do |format|  
            format.js { render partial:'users/friendsearchResult' }
        end
      else 
        respond_to do |format|
            flash.now[:alert]='No User Found!'
            format.js{render partial:'users/friendsearchResult' }
        end

      end
    else
      respond_to do |format|
        flash.now[:alert]='Please Enter name or Email'
        format.js{render partial:'users/friendsearchResult' }
    end

    end

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friendsearchResult.js.erb
document.querySelector('#friendssearchResult').innerHTML ='<%= j render 'users/friendsearchResult1' %>';

app/views/users/_friendsearchResult1.html.erb
<div class="results-block">
  <%= render 'layouts/flashmessages' %>
</div>

<% if @friends %>
   
        <div class="card card-header results-block">
            <table class="col-md-12">
                <tbody>
                <% @friends.each do |friend| %>
                <tr>
                    <td><strong>Email : </strong> <%= friend.email %></td>
                    <td><strong>Name : </strong> <%= friend.full_name %></td>
                    <td><strong>Actions :</strong> 
                        <%= link_to "View Profile",user_path(friend.id),class:"btn btn-success"%>
                        <% if current_user.not_friends_with?(friend.id)%>
                            <%= link_to 'Follow Friend ?',friendships_path(user:current_user,friend:friend),class:"btn btn-success",method: :post%>
                        <%else%>
                        <span class="badge text-bg-primary">
                                You are Already friends
                        </span>
                        <%end%>
                    </td>
                </tr> 
                    
                <%end%>
                </tbody>
            </table >
                
        </div>
    
<% end %>

app/views/users/_stocksearchResult.js.erb
  console.log("Hello")

document.querySelector('#stocksearchResult').innerHTML ='<%= j render 'users/stocksearchResult1' %>';

app/views/users/_stocksearchResult1.html.erb
<div class="results-block">
  <%= render 'layouts/flashmessages' %>
</div>

<% if @stock.present? && @stock.ast_price !=0.0  %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.ast_price %>
    <% if current_user.can_track_stock?(@stock.ticker)%>
        <%= link_to 'Add To Portfolio',user_stocks_path(user:current_user,ticker:@stock.ticker),class:"btn btn-success",method: :post%>
    <%else%>
    <span class="badge text-bg-success">
        You are already tracking
        <% if !current_user.under_stock_limit? %>
                 8 stocks
        <%end%>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
                this stock
        <%end%>
    </span>
    <%end%>
</div>
<% end %>

app/views/users/my_friends.html.erb
<h1>My Friends</h1>
<h2 class="py-5">Search Friends</h2>

  

<%= form_tag search_friend_path, remote: true, method: :get,id:"search_friends_form" do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Email or Name", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success " do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div id="friendssearchResult">
   
    </div>
  <%= render 'friends/list' %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<h2 class="py-5">Search Stocks</h2>

  

<%= form_tag search_stock_path, remote: true, method: :get,id:"search_stocks_form" do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success search-button", id: "search_button" do %>
          <span id="search_icon"><%= fa_icon 'search 2x' %></span>
          <span id="loading_spinner" class="spinner-border spinner-border-sm" role="status" aria-hidden="true" style="display: none;"></span>
        <% end %>
      </div>
    </div>
  <% end %>
<div id="myModal" class="modal">
    <div class="spinner-border" style="width: 3rem; height: 3rem;" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow" style="width: 3rem; height: 3rem;" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
</div>
<div id="stocksearchResult">
   
</div>
<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<%end%>

app/views/users/show.html.erb
<h2> User Profile </h2>
 
<table class="col-md-12">
    <tbody>
        <tr>
            <td><strong>Email : </strong> <%=  @user.email %></td>
            <td><strong>Name : </strong> <%=  @user.full_name %></td>
            <td><strong>Actions :</strong> 
                
                <% if current_user.not_friends_with?( @user.id)%>
                    <%= link_to 'Follow Friend ?',friendships_path(user:current_user,friend: @user),class:"btn btn-success",method: :post%>
                <%else%>
                <span class="badge text-bg-primary">
                        You are Already friends
                </span>
                <%end%>
            </td>
        </tr> 
    </tbody>
</table >
<div class="my-3">
<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<%else%>
 <p class="lead">This user is not currently tracking any Stocks</p>
<%end%>
</div>
                