config/routes.rb
Rails.application.routes.draw do
 
  resources :user_stocks,only:[:create,:destroy]
  resources :friendships,only:[:create,:destroy]
  
  
  devise_for :users
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'my_portfolio',to:'users#my_portfolio'
  get 'search_stock',to:'stocks#quote',as: 'search_stock'

  get 'my_friends',to:'users#my_friends'
  get 'search_friend',to:'users#search',as: 'search_friend'


  # get 'Stocks',to:'stocks#stock_symbols'
 

  # get 'search',to:'stocks#symbol_search'
  #  get '_search/:ticker_symbol',to:'stocks#search'
  resources :users,only:[:show]
 get 'similarity',to:'stocks#similarity_index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_flashmessages.html.erb
<% if notice %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>
<% if alert %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light"">
 
    <div class="container">
      
        <%= link_to 'Finance Tracker',root_path,class:'navbar-brand'%>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <% if user_signed_in?%>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <%= link_to 'My Portfolio',my_portfolio_path,class:"nav-link  #{'active' if current_page?(my_portfolio_path)}"%>
                    </li>
                    <li class="nav-item">
                         <%= link_to 'My Friends',my_friends_path,class:"nav-link  #{'active' if current_page?(my_friends_path)}"%>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Profile
                        </a>
                    <ul class="dropdown-menu">
                        
                        <%= link_to edit_user_registration_path,class:"dropdown-item" do %>
                            <%=fa_icon 'edit'%> Edit Profile
                        <%end%>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                    </li>
                    
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item user-name">
                        <%=fa_icon 'user'%> <%= current_user.full_name%>
                    </li>
                    <li class="nav-item ">
                    <%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger logout-btn" %>

                    </li>
                </ul>
            
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        <%end%>
    </div>
    
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <%= render 'layouts/navigation' %>
     <div class="container">
        <%= render 'layouts/flashmessages' %>
        <%= yield %>
     </div>
  </body>
</html>